POST http://localhost:8081/book
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name": "gcdxy","isbn":"124"}

###

GET http://localhost:8081/book/8
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###

GET http://localhost:8081/books
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###

PUT http://localhost:8081/book/2/loveadd
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###
GET http://42.7.245.102:8081/book/search/124
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###